### ISSUE TITLE
Configurable KV location

### ISSUE THREAD

**Issue by manveru** [gherynos/vault-backend#1]
First of all, thanks a lot for this project, it's a shame this isn't a part of terraform yet.

May I suggest though to make the location of the KV store, which is hardcoded to `secret`, configurable just like the `VAULT_PREFIX`? I'd be happy to make a PR for this, if you're not opposed to the idea.

**Comment by gherynos** [comment]
You're very welcome Sir 😃 I'm glad the tool is useful, and you're quite right: it should be supported in Terraform out-of-the-box.

It's a great idea, and I'll be more than happy to review your PR!

**Comment by gherynos** [comment]
Resolved :)
